check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.27.0"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "odh-jupyterhub"
  registry-project: "jupyterhub-idle-culler"
  registry-secret: "odh-jupyterhub-thoth-pusher-secret"