host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pip

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - vpavlin
        - LaVLaS
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true